# Generated by Django 4.1.5 on 2023-02-10 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,30}$', ['Service name demands: contains 2-30 letters.'])])),
                ('address', models.CharField(max_length=128)),
                ('photos', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'c_services',
            },
        ),
    ]
