# Generated by Django 4.1.7 on 2023-02-21 11:02

import django.db.models.deletion
from django.db import migrations, models

import apps.extra_tools.services


class Migration(migrations.Migration):

    dependencies = [
        ('c_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='photos',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='PhotoServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_photos', models.ImageField(upload_to=apps.extra_tools.services.upload_services_photos)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_photos', to='c_services.servicemodel')),
            ],
            options={
                'db_table': 'services_photos',
            },
        ),
    ]
