# Generated by Django 4.1.7 on 2023-02-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_services', '0002_alter_servicemodel_options_alter_servicemodel_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoservicemodel',
            old_name='service_photos',
            new_name='photos',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='photos',
        ),
        migrations.AlterField(
            model_name='photoservicemodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='c_services.servicemodel'),
        ),
    ]
