# Generated by Django 4.1.5 on 2023-01-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('photos', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
