# Generated by Django 4.1.5 on 2023-02-10 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^(1[4-9]|[2-9]\\d)$', ['For 14+ y.o. users.'])]),
        ),
    ]
