# Generated by Django 4.1.5 on 2023-02-10 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\s])[^\\s]{8,20}$', ['Password demands: 8-20 chars', 'contains a number(0-9)', 'contains at least one UpperCase latter', 'contains at least one LowerCase latter', 'contains at least one SpecialChar latter.'])]),
        ),
    ]
