# Generated by Django 4.1.7 on 2023-02-21 17:40

from django.db import migrations, models

import apps.extra_tools.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to=apps.extra_tools.services.upload_users_photos),
        ),
    ]
