from django.urls import path

from .views import (
    ActivateByTokenView,
    AddOrderToUserView,
    AddUserPhotoView,
    ChangeEmployeeServiceView,
    ChangeUserServiceView,
    DeleteUserView,
    EmployeeRejectRequestView,
    GetSelfUserView,
    GetUserByOrderIdView,
    GetUserByTokenView,
    ListBestEmployeeView,
    ListUserOrdersView,
    ProfileUpdateView,
    RetrieveDestroyUserView,
    ToAdminView,
    ToEmployeeView,
    ToUserView,
    UserActivateView,
    UserDeactivateView,
    UserListCreateView,
)

urlpatterns = [
    path('', UserListCreateView.as_view(), name='users_list_create'),
    path('/orders', ListUserOrdersView.as_view(), name='users_list_orders'),
    path('/self', GetSelfUserView.as_view(), name='users_get_self_user'),
    path('/change_service/<int:pk>', ChangeUserServiceView.as_view(), name='users_change_service'),
    path('/<int:user>/change_employee_service/<int:service>', ChangeEmployeeServiceView.as_view(), name='users_change_employee_service'),
    path('/<int:pk>/activate', UserActivateView.as_view(), name='users_activate'),
    path('/<int:pk>/deactivate', UserDeactivateView.as_view(), name='users_deactivate'),
    path('/<int:pk>/to_admin', ToAdminView.as_view(), name='users_change_to_admin'),
    path('/<int:pk>/to_user', ToUserView.as_view(), name='users_change_to_user'),
    path('/<int:pk>/to_employee', ToEmployeeView.as_view(), name='users_change_to_employee'),
    path('/new_order', AddOrderToUserView.as_view(), name='users_make_new_order'),
    path('/profile_update', ProfileUpdateView.as_view(), name='users_profile_update'),
    path('/add_photo', AddUserPhotoView.as_view(), name='users_add_photo_to_profile'),
    path('/best_employees', ListBestEmployeeView.as_view(), name='users_list_best_five_employees'),
    path('/request_of_reject/<int:pk>', EmployeeRejectRequestView.as_view(), name='users_request_of_reject_order'),
    path('/<int:pk>/delete', DeleteUserView.as_view(), name='users_delete'),
    path('/<int:pk>', RetrieveDestroyUserView.as_view(), name='users_get_by_id'),
    path('/get_by_order/<int:pk>', GetUserByOrderIdView.as_view(), name='users_get_by_order_id'),
    path('/activate_by_token/<str:token>', ActivateByTokenView.as_view(), name='users_activate_by_token'),
    path('/get_by_token/<str:token>', GetUserByTokenView.as_view(), name='users_get_by_token'),
]
