# Generated by Django 4.1.5 on 2023-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=128)),
                ('task_description', models.TextField()),
                ('date', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
                ('employees_quantity', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'orders_status',
            },
        ),
    ]
