# Generated by Django 4.1.6 on 2023-02-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ordermodel_photos_alter_ordermodel_footage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddPhotoToOrderModel',
            new_name='PhotoOrderModel',
        ),
    ]
