# Generated by Django 4.1.6 on 2023-02-11 12:16

from django.db import migrations, models

import backend.apps.orders.services


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_addphototoordermodel_photoordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='photo',
            field=models.ImageField(default=1, upload_to=backend.apps.orders.services.upload_photos),
            preserve_default=False,
        ),
    ]
