# Generated by Django 4.1.6 on 2023-02-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='photo',
        ),
    ]
