# Generated by Django 4.1.6 on 2023-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_ordermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
