# Generated by Django 4.1.6 on 2023-02-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ordermodel_date_alter_ordermodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
