# Generated by Django 4.1.7 on 2023-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_ordermodel_price_alter_ordermodel_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['id']},
        ),
    ]
