# Generated by Django 4.1.5 on 2023-01-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='services.servicemodel'),
            preserve_default=False,
        ),
    ]
