# Generated by Django 4.1.5 on 2023-01-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0004_alter_usermodel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='services.servicemodel'),
        ),
    ]
